apiVersion: v1
kind: Pod
metadata:
  name: api-backend
spec:
  containers:
  - name: api-backend
    image: your-docker-image
    ports:
    - containerPort: 3000
    envFrom:
    - configMapRef:
        name: api-config
