stages:
  - build
  - deploy

variables:
  IMAGE: "tu-registro/api:latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s/api-deployment.yaml
    - kubectl apply -f k8s/mysql-deployment.yaml
